import { Document } from "mongoose";

export enum Currency {
  INCH = "INCH",
  AAVE = "AAVE",
  ABT = "ABT",
  ACH = "ACH",
  ACS = "ACS",
  ADA = "ADA",
  AED = "AED",
  AERGO = "AERGO",
  AERO = "AERO",
  AFN = "AFN",
  AGLD = "AGLD",
  AIOZ = "AIOZ",
  ALCX = "ALCX",
  ALEPH = "ALEPH",
  ALGO = "ALGO",
  ALICE = "ALICE",
  ALL = "ALL",
  AMD = "AMD",
  AMP = "AMP",
  ANG = "ANG",
  ANKR = "ANKR",
  ANT = "ANT",
  AO = "AO",
  APE = "APE",
  API3 = "API3",
  APT = "APT",
  ARB = "ARB",
  ARP = "ARP",
  ARS = "ARS",
  ASM = "ASM",
  AST = "AST",
  ATA = "ATA",
  ATOM = "ATOM",
  AUCTION = "AUCTION",
  AUD = "AUD",
  AUDIO = "AUDIO",
  AURORA = "AURORA",
  AVAX = "AVAX",
  AVT = "AVT",
  AWG = "AWG",
  AXL = "AXL",
  AXS = "AXS",
  AZN = "AZN",
  BADGER = "BADGER",
  BAL = "BAL",
  BAM = "BAM",
  BAND = "BAND",
  BAT = "BAT",
  BBD = "BBD",
  BCH = "BCH",
  BDT = "BDT",
  BGN = "BGN",
  BHD = "BHD",
  BICO = "BICO",
  BIF = "BIF",
  BIGTIME = "BIGTIME",
  BIT = "BIT",
  BLUR = "BLUR",
  BLZ = "BLZ",
  BMD = "BMD",
  BND = "BND",
  BNT = "BNT",
  BOB = "BOB",
  BOBA = "BOBA",
  BOND = "BOND",
  BONK = "BONK",
  BRL = "BRL",
  BSD = "BSD",
  BSV = "BSV",
  BTC = "BTC",
  BTN = "BTN",
  BTRST = "BTRST",
  BUSD = "BUSD",
  BWP = "BWP",
  BYN = "BYN",
  BYR = "BYR",
  BZD = "BZD",
  C98 = "C98",
  CAD = "CAD",
  CBETH = "CBETH",
  CDF = "CDF",
  CELR = "CELR",
  CGLD = "CGLD",
  CHF = "CHF",
  CHZ = "CHZ",
  CLF = "CLF",
  CLP = "CLP",
  CLV = "CLV",
  CNH = "CNH",
  CNY = "CNY",
  COMP = "COMP",
  COP = "COP",
  COTI = "COTI",
  COVAL = "COVAL",
  CRC = "CRC",
  CRO = "CRO",
  CRPT = "CRPT",
  CRV = "CRV",
  CTSI = "CTSI",
  CTX = "CTX",
  CUC = "CUC",
  CUP = "CUP",
  CVC = "CVC",
  CVE = "CVE",
  CVX = "CVX",
  CZK = "CZK",
  DAI = "DAI",
  DAR = "DAR",
  DASH = "DASH",
  DDX = "DDX",
  DESO = "DESO",
  DEXT = "DEXT",
  DIA = "DIA",
  DIMO = "DIMO",
  DJF = "DJF",
  DKK = "DKK",
  DNT = "DNT",
  DOGE = "DOGE",
  DOP = "DOP",
  DOT = "DOT",
  DREP = "DREP",
  DYP = "DYP",
  DZD = "DZD",
  EEK = "EEK",
  EGLD = "EGLD",
  EGP = "EGP",
  ELA = "ELA",
  ENJ = "ENJ",
  ENS = "ENS",
  EOS = "EOS",
  ERN = "ERN",
  ETB = "ETB",
  ETC = "ETC",
  ETH = "ETH",
  ETH2 = "ETH2",
  EUR = "EUR",
  EUROC = "EUROC",
  FARM = "FARM",
  FET = "FET",
  FIDA = "FIDA",
  FIL = "FIL",
  FIS = "FIS",
  FJD = "FJD",
  FKP = "FKP",
  FLOW = "FLOW",
  FLR = "FLR",
  FORT = "FORT",
  FORTH = "FORTH",
  FOX = "FOX",
  FX = "FX",
  GAL = "GAL",
  GALA = "GALA",
  GBP = "GBP",
  GEL = "GEL",
  GFI = "GFI",
  GGP = "GGP",
  GHS = "GHS",
  GHST = "GHST",
  GIP = "GIP",
  GLM = "GLM",
  GMD = "GMD",
  GMT = "GMT",
  GNF = "GNF",
  GNO = "GNO",
  GNT = "GNT",
  GODS = "GODS",
  GRT = "GRT",
  GST = "GST",
  GTC = "GTC",
  GTQ = "GTQ",
  GUSD = "GUSD",
  GYD = "GYD",
  GYEN = "GYEN",
  HBAR = "HBAR",
  HFT = "HFT",
  HIGH = "HIGH",
  HKD = "HKD",
  HNL = "HNL",
  HNT = "HNT",
  HONEY = "HONEY",
  HOPR = "HOPR",
  HRK = "HRK",
  HTG = "HTG",
  HUF = "HUF",
  ICP = "ICP",
  IDEX = "IDEX",
  IDR = "IDR",
  ILS = "ILS",
  ILV = "ILV",
  IMP = "IMP",
  IMX = "IMX",
  INDEX = "INDEX",
  INJ = "INJ",
  INR = "INR",
  IOTX = "IOTX",
  IQD = "IQD",
  IRR = "IRR",
  ISK = "ISK",
  JASMY = "JASMY",
  JEP = "JEP",
  JMD = "JMD",
  JOD = "JOD",
  JPY = "JPY",
  JTO = "JTO",
  JUP = "JUP",
  KAV = "KAV",
  KEEP = "KEEP",
  KES = "KES",
  KGS = "KGS",
  KHR = "KHR",
  KMF = "KMF",
  KNC = "KNC",
  KPW = "KPW",
  KRL = "KRL",
  KRW = "KRW",
  KSM = "KSM",
  KWD = "KWD",
  KYD = "KYD",
  KZT = "KZT",
  LAK = "LAK",
  LBP = "LBP",
  LCX = "LCX",
  LDO = "LDO",
  LINK = "LINK",
  LIT = "LIT",
  LKR = "LKR",
  LOKA = "LOKA",
  LOOM = "LOOM",
  LPT = "LPT",
  LQT = "LQT",
  LRC = "LRC",
  LRD = "LRD",
  LSL = "LSL",
  LSETH = "LSETH",
  LTC = "LTC",
  LTL = "LTL",
  LVL = "LVL",
  LYD = "LYD",
  MAD = "MAD",
  MAGIC = "MAGIC",
  MANA = "MANA",
  MASK = "MASK",
  MATH = "MATH",
  MATIC = "MATIC",
  MCO2 = "MCO2",
  MDL = "MDL",
  MDT = "MDT",
  MEDIA = "MEDIA",
  METIS = "METIS",
  MGA = "MGA",
  MINA = "MINA",
  MIR = "MIR",
  MKD = "MKD",
  MKR = "MKR",
  MLN = "MLN",
  MMK = "MMK",
  MNE = "MNE",
  MNT = "MNT",
  MOBIL = "MOBIL",
  MONA = "MONA",
  MOP = "MOP",
  MPL = "MPL",
  MRO = "MRO",
  MRU = "MRU",
  MSOL = "MSOL",
  MTL = "MTL",
  MULTI = "MULTI",
  MUSE = "MUSE",
  MVR = "MVR",
  MWK = "MWK",
  MXC = "MXC",
  MXN = "MXN",
  MYR = "MYR",
  MZN = "MZN",
  NAD = "NAD",
  NCT = "NCT",
  NEAR = "NEAR",
  NEST = "NEST",
  NGN = "NGN",
  NIO = "NIO",
  NKN = "NKN",
  NMR = "NMR",
  NOK = "NOK",
  NPR = "NPR",
  NU = "NU",
  NZD = "NZD",
  OCEAN = "OCEAN",
  OGN = "OGN",
  OMG = "OMG",
  OMR = "OMR",
  OND = "OND",
  OO = "OO",
  KO = "KO",
  ORCA = "ORCA",
  ORN = "ORN",
  OSMO = "OSMO",
  OXT = "OXT",
  PAB = "PAB",
  PAX = "PAX",
  PEN = "PEN",
  PERP = "PERP",
  PGK = "PGK",
  PHP = "PHP",
  PKR = "PKR",
  PLA = "PLA",
  PLN = "PLN",
  PLU = "PLU",
  PNG = "PNG",
  POLS = "POLS",
  POLY = "POLY",
  POND = "POND",
  POWR = "POWR",
  PRIME = "PRIME",
  PRO = "PRO",
  PRQ = "PRQ",
  PUNDIX = "PUNDIX",
  PYG = "PYG",
  PYR = "PYR",
  PYUSD = "PYUSD",
  QAR = "QAR",
  QI = "QI",
  QNT = "QNT",
  QSP = "QSP",
  QUICK = "QUICK",
  RAD = "RAD",
  RAI = "RAI",
  RARE = "RARE",
  RARI = "RARI",
  RBN = "RBN",
  REN = "REN",
  RENDER = "RENDER",
  REP = "REP",
  REPV2 = "REPV2",
  REQ = "REQ",
  RGT = "RGT",
  RLC = "RLC",
  RLY = "RLY",
  RND = "RND",
  RON = "RON",
  ROSE = "ROSE",
  RPL = "RPL",
  RSD = "RSD",
  RUB = "RUB",
  RWF = "RWF",
  SAND = "SAND",
  SAR = "SAR",
  SBD = "SBD",
  SCR = "SCR",
  SDG = "SDG",
  SEAM = "SEAM",
  SEI = "SEI",
  SEK = "SEK",
  SGD = "SGD",
  SHIB = "SHIB",
  SHP = "SHP",
  SHPING = "SHPING",
  SKK = "SKK",
  SKL = "SKL",
  SLL = "SLL",
  SNT = "SNT",
  SNX = "SNX",
  SOL = "SOL",
  SOS = "SOS",
  SPA = "SPA",
  SPELL = "SPELL",
  SRD = "SRD",
  SSP = "SSP",
  STD = "STD",
  STG = "STG",
  STORJ = "STORJ",
  STRK = "STRK",
  STX = "STX",
  SUI = "SUI",
  SUKU = "SUKU",
  SUPER = "SUPER",
  SUSHI = "SUSHI",
  SVC = "SVC",
  SWFTC = "SWFTC",
  SYLO = "SYLO",
  SYN = "SYN",
  SYP = "SYP",
  SZL = "SZL",
  THB = "THB",
  TIA = "TIA",
  TIME = "TIME",
  TJS = "TJS",
  TMM = "TMM",
  TMT = "TMT",
  TND = "TND",
  TONE = "TONE",
  TOP = "TOP",
  TRAC = "TRAC",
  TRB = "TRB",
  TRIBE = "TRIBE",
  TRU = "TRU",
  TRY = "TRY",
  TTD = "TTD",
  TVK = "TVK",
  TWD = "TWD",
  TZS = "TZS",
  UAH = "UAH",
  UGX = "UGX",
  UMA = "UMA",
  UNF = "UNF",
  UNI = "UNI",
  UPI = "UPI",
  USD = "USD",
  USDC = "USDC",
  USDT = "USDT",
  UST = "UST",
  UYU = "UYU",
  UZS = "UZS",
  VAR = "VAR",
  VEF = "VEF",
  VELO = "VELO",
  VES = "VES",
  VET = "VET",
  VGX = "VGX",
  VND = "VND",
  VOXEL = "VOXEL",
  VTHO = "VTHO",
  VUV = "VUV",
  WAMPL = "WAMPL",
  WAXL = "WAXL",
  WBTC = "WBTC",
  WCFG = "WCFG",
  WLUNA = "WLUNA",
  WST = "WST",
  XAF = "XAF",
  XAG = "XAG",
  XAU = "XAU",
  XCD = "XCD",
  XCN = "XCN",
  XDR = "XDR",
  XLM = "XLM",
  XMON = "XMON",
  XOF = "XOF",
  XPD = "XPD",
  XPF = "XPF",
  XPT = "XPT",
  XRP = "XRP",
  XTZ = "XTZ",
  XYO = "XYO",
  YER = "YER",
  YFI = "YFI",
  YFII = "YFII",
  ZAR = "ZAR",
  ZEC = "ZEC",
  ZEN = "ZEN",
  ZETA = "ZETA",
  ZMK = "ZMK",
  ZMW = "ZMW",
  ZRX = "ZRX",
  ZWD = "ZWD",
}

export enum Country {
  AF = "AF", // Afghanistan
  AL = "AL", // Albania
  DZ = "DZ", // Algeria
  AS = "AS", // American Samoa
  AD = "AD", // Andorra
  AO = "AO", // Angola
  AI = "AI", // Anguilla
  AQ = "AQ", // Antarctica
  AG = "AG", // Antigua and Barbuda
  AR = "AR", // Argentina
  AM = "AM", // Armenia
  AW = "AW", // Aruba
  AU = "AU", // Australia
  AT = "AT", // Austria
  AZ = "AZ", // Azerbaijan
  BS = "BS", // Bahamas
  BH = "BH", // Bahrain
  BD = "BD", // Bangladesh
  BB = "BB", // Barbados
  BY = "BY", // Belarus
  BE = "BE", // Belgium
  BZ = "BZ", // Belize
  BJ = "BJ", // Benin
  BM = "BM", // Bermuda
  BT = "BT", // Bhutan
  BO = "BO", // Bolivia
  BQ = "BQ", // Bonaire, Sint Eustatius and Saba
  BA = "BA", // Bosnia and Herzegovina
  BW = "BW", // Botswana
  BV = "BV", // Bouvet Island
  BR = "BR", // Brazil
  IO = "IO", // British Indian Ocean Territory
  BN = "BN", // Brunei Darussalam
  BG = "BG", // Bulgaria
  BF = "BF", // Burkina Faso
  BI = "BI", // Burundi
  CV = "CV", // Cabo Verde
  KH = "KH", // Cambodia
  CM = "CM", // Cameroon
  CA = "CA", // Canada
  KY = "KY", // Cayman Islands
  CF = "CF", // Central African Republic
  TD = "TD", // Chad
  CL = "CL", // Chile
  CN = "CN", // China
  CX = "CX", // Christmas Island
  CC = "CC", // Cocos (Keeling) Islands
  CO = "CO", // Colombia
  KM = "KM", // Comoros
  CD = "CD", // Congo, Democratic Republic of the
  CG = "CG", // Congo
  CK = "CK", // Cook Islands
  CR = "CR", // Costa Rica
  HR = "HR", // Croatia
  CU = "CU", // Cuba
  CW = "CW", // Curaçao
  CY = "CY", // Cyprus
  CZ = "CZ", // Czechia
  CI = "CI", // Côte d'Ivoire
  DK = "DK", // Denmark
  DJ = "DJ", // Djibouti
  DM = "DM", // Dominica
  DO = "DO", // Dominican Republic
  EC = "EC", // Ecuador
  EG = "EG", // Egypt
  SV = "SV", // El Salvador
  GQ = "GQ", // Equatorial Guinea
  ER = "ER", // Eritrea
  EE = "EE", // Estonia
  SZ = "SZ", // Eswatini
  ET = "ET", // Ethiopia
  FK = "FK", // Falkland Islands (Malvinas)
  FO = "FO", // Faroe Islands
  FJ = "FJ", // Fiji
  FI = "FI", // Finland
  FR = "FR", // France
  GF = "GF", // French Guiana
  PF = "PF", // French Polynesia
  TF = "TF", // French Southern Territories
  GA = "GA", // Gabon
  GM = "GM", // Gambia
  GE = "GE", // Georgia
  DE = "DE", // Germany
  GH = "GH", // Ghana
  GI = "GI", // Gibraltar
  GR = "GR", // Greece
  GL = "GL", // Greenland
  GD = "GD", // Grenada
  GP = "GP", // Guadeloupe
  GU = "GU", // Guam
  GT = "GT", // Guatemala
  GG = "GG", // Guernsey
  GN = "GN", // Guinea
  GW = "GW", // Guinea-Bissau
  GY = "GY", // Guyana
  HT = "HT", // Haiti
  HM = "HM", // Heard Island and McDonald Islands
  VA = "VA", // Holy See
  HN = "HN", // Honduras
  HK = "HK", // Hong Kong
  HU = "HU", // Hungary
  IS = "IS", // Iceland
  IN = "IN", // India
  ID = "ID", // Indonesia
  IR = "IR", // Iran
  IQ = "IQ", // Iraq
  IE = "IE", // Ireland
  IM = "IM", // Isle of Man
  IL = "IL", // Israel
  IT = "IT", // Italy
  JM = "JM", // Jamaica
  JP = "JP", // Japan
  JE = "JE", // Jersey
  JO = "JO", // Jordan
  KZ = "KZ", // Kazakhstan
  KE = "KE", // Kenya
  KI = "KI", // Kiribati
  KP = "KP", // Korea, Democratic People's Republic of
  KR = "KR", // Korea, Republic of
  KW = "KW", // Kuwait
  KG = "KG", // Kyrgyzstan
  LA = "LA", // Lao People's Democratic Republic
  LV = "LV", // Latvia
  LB = "LB", // Lebanon
  LS = "LS", // Lesotho
  LR = "LR", // Liberia
  LY = "LY", // Libya
  LI = "LI", // Liechtenstein
  LT = "LT", // Lithuania
  LU = "LU", // Luxembourg
  MO = "MO", // Macao
  MG = "MG", // Madagascar
  MW = "MW", // Malawi
  MY = "MY", // Malaysia
  MV = "MV", // Maldives
  ML = "ML", // Mali
  MT = "MT", // Malta
  MH = "MH", // Marshall Islands
  MQ = "MQ", // Martinique
  MR = "MR", // Mauritania
  MU = "MU", // Mauritius
  YT = "YT", // Mayotte
  MX = "MX", // Mexico
  FM = "FM", // Micronesia
  MD = "MD", // Moldova
  MC = "MC", // Monaco
  MN = "MN", // Mongolia
  ME = "ME", // Montenegro
  MS = "MS", // Montserrat
  MA = "MA", // Morocco
  MZ = "MZ", // Mozambique
  MM = "MM", // Myanmar
  NA = "NA", // Namibia
  NR = "NR", // Nauru
  NP = "NP", // Nepal
  NL = "NL", // Netherlands
  NC = "NC", // New Caledonia
  NZ = "NZ", // New Zealand
  NI = "NI", // Nicaragua
  NE = "NE", // Niger
  NG = "NG", // Nigeria
  NU = "NU", // Niue
  NF = "NF", // Norfolk Island
  MK = "MK", // North Macedonia
  MP = "MP", // Northern Mariana Islands
  NO = "NO", // Norway
  OM = "OM", // Oman
  PK = "PK", // Pakistan
  PW = "PW", // Palau
  PS = "PS", // Palestine, State of
  PA = "PA", // Panama
  PG = "PG", // Papua New Guinea
  PY = "PY", // Paraguay
  PE = "PE", // Peru
  PH = "PH", // Philippines
  PN = "PN", // Pitcairn
  PL = "PL", // Poland
  PT = "PT", // Portugal
  PR = "PR", // Puerto Rico
  QA = "QA", // Qatar
  RO = "RO", // Romania
  RU = "RU", // Russian Federation
  RW = "RW", // Rwanda
  RE = "RE", // Réunion
  BL = "BL", // Saint Barthélemy
  SH = "SH", // Saint Helena, Ascension and Tristan da Cunha
  KN = "KN", // Saint Kitts and Nevis
  LC = "LC", // Saint Lucia
  MF = "MF", // Saint Martin (French part)
  PM = "PM", // Saint Pierre and Miquelon
  VC = "VC", // Saint Vincent and the Grenadines
  WS = "WS", // Samoa
  SM = "SM", // San Marino
  ST = "ST", // Sao Tome and Principe
  SA = "SA", // Saudi Arabia
  SN = "SN", // Senegal
  RS = "RS", // Serbia
  SC = "SC", // Seychelles
  SL = "SL", // Sierra Leone
  SG = "SG", // Singapore
  SX = "SX", // Sint Maarten (Dutch part)
  SK = "SK", // Slovakia
  SI = "SI", // Slovenia
  SB = "SB", // Solomon Islands
  SO = "SO", // Somalia
  ZA = "ZA", // South Africa
  GS = "GS", // South Georgia and the South Sandwich Islands
  SS = "SS", // South Sudan
  ES = "ES", // Spain
  LK = "LK", // Sri Lanka
  SD = "SD", // Sudan
  SR = "SR", // Suriname
  SJ = "SJ", // Svalbard and Jan Mayen
  SE = "SE", // Sweden
  CH = "CH", // Switzerland
  SY = "SY", // Syrian Arab Republic
  TW = "TW", // Taiwan
  TJ = "TJ", // Tajikistan
  TZ = "TZ", // Tanzania
  TH = "TH", // Thailand
  TL = "TL", // Timor-Leste
  TG = "TG", // Togo
  TK = "TK", // Tokelau
  TO = "TO", // Tonga
  TT = "TT", // Trinidad and Tobago
  TN = "TN", // Tunisia
  TR = "TR", // Turkey
  TM = "TM", // Turkmenistan
  TC = "TC", // Turks and Caicos Islands
  TV = "TV", // Tuvalu
  UG = "UG", // Uganda
  UA = "UA", // Ukraine
  AE = "AE", // United Arab Emirates
  GB = "GB", // United Kingdom
  UM = "UM", // United States Minor Outlying Islands
  US = "US", // United States of America
  UY = "UY", // Uruguay
  UZ = "UZ", // Uzbekistan
  VU = "VU", // Vanuatu
  VE = "VE", // Venezuela
  VN = "VN", // Viet Nam
  VG = "VG", // Virgin Islands (British)
  VI = "VI", // Virgin Islands (U.S.)
  WF = "WF", // Wallis and Futuna
  EH = "EH", // Western Sahara
  YE = "YE", // Yemen
  ZM = "ZM", // Zambia
  ZW = "ZW", // Zimbabwe
  AX = "AX", // Åland Islands
  XA = "XA", // User-assigned: XA
  XB = "XB", // User-assigned: XB
  XC = "XC", // User-assigned: XC
  XD = "XD", // User-assigned: XD
  XE = "XE", // User-assigned: XE
  XF = "XF", // User-assigned: XF
  XG = "XG", // User-assigned: XG
  XH = "XH", // User-assigned: XH
  XI = "XI", // User-assigned: XI
  XJ = "XJ", // User-assigned: XJ
  XK = "XK", // User-assigned: XK (commonly used for Kosovo)
  XL = "XL", // User-assigned: XL
  XM = "XM", // User-assigned: XM
  XN = "XN", // User-assigned: XN
  XO = "XO", // User-assigned: XO
  XP = "XP", // User-assigned: XP
  XQ = "XQ", // User-assigned: XQ
  XR = "XR", // User-assigned: XR
  XS = "XS", // User-assigned: XS
  XT = "XT", // User-assigned: XT
  XU = "XU", // User-assigned: XU
  XV = "XV", // User-assigned: XV
  XW = "XW", // User-assigned: XW
  XY = "XY", // User-assigned: XY
  XZ = "XZ", // User-assigned: XZ
}

export enum type {
  DEPOSIT = "DEPOSIT",
  TRANSFER = "TRANSFER",
  EXTERNAL_PAYMENT = "EXTERNAL_PAYMENT",
  WITHDRAWAL = "WITHDRAWAL",
  REFUND = "REFUND",
  OTHER = "OTHER",
}

export enum transactionState {
  CREATED = "CREATED",
  PROCESSING = "PROCESSING",
  SENT = "SENT",
  EXPIRED = "EXPIRED",
  DECLINED = "DECLINED",
  SUSPENDED = "SUSPENDED",
  REFUNDED = "REFUNDED",
  SUCCESSFUL = "SUCCESSFUL",
  REVERSED = "REVERSED",
}

interface AmountDetails {
  transactionAmount: number;
  transactionCurrency: Currency;
  country: Country;
}

interface DeviceData {
  batteryLevel: number;
  deviceLatitude: number;
  deviceLongitude: number;
  ipAddress: string;
  deviceIdentifier: string;
  vpnUsed: boolean;
  operatingSystem: string;
  deviceMaker: string;
  deviceModel: string;
  deviceYear: string;
  appVersion: string;
}

interface Tag {
  key: string;
  value: string;
}

export interface Transaction extends Document {
  type: type;
  transactionId: string;
  timestamp: number;
  originUserId: string;
  destinationUserId: string;
  transactionState: transactionState;
  originAmountDetails: AmountDetails;
  destinationAmountDetails: AmountDetails;
  promotionCodeUsed: boolean;
  reference: string;
  originDeviceData: DeviceData;
  destinationDeviceData: DeviceData;
  tags: Tag[];
  description: string;
}
  