import cron from "node-cron";
import TransactionModel from "../models/transaction";
import { type, transactionState } from "../types/transaction";

let task: cron.ScheduledTask | null = null;

export const startTransactionGenerator = () => {
  if (task) {
    console.log("Transaction generator is already running.");
    return;
  }

  task = cron.schedule("* * * * * *", async () => {
    try {
      const newTransaction = new TransactionModel({
        type: type.TRANSFER,
        transactionId: `txn_${Date.now()}`,
        timestamp: Date.now(),
        originUserId: "user1",
        destinationUserId: "user2",
        transactionState: transactionState.CREATED,
        originAmountDetails: {
          transactionAmount: Math.random() * 1000,
          transactionCurrency: "USD",
          country: "US",
        },
        destinationAmountDetails: {
          transactionAmount: Math.random() * 1000,
          transactionCurrency: "USD",
          country: "US",
        },
        promotionCodeUsed: false,
        reference: "Generated by CRON",
        originDeviceData: {
          batteryLevel: 100,
          deviceLatitude: 37.7749,
          deviceLongitude: -122.4194,
          ipAddress: "127.0.0.1",
          deviceIdentifier: "device1",
          vpnUsed: false,
          operatingSystem: "iOS",
          deviceMaker: "Apple",
          deviceModel: "iPhone 12",
          deviceYear: "2020",
          appVersion: "1.0.0",
        },
        destinationDeviceData: {
          batteryLevel: 100,
          deviceLatitude: 37.7749,
          deviceLongitude: -122.4194,
          ipAddress: "127.0.0.1",
          deviceIdentifier: "device2",
          vpnUsed: false,
          operatingSystem: "iOS",
          deviceMaker: "Apple",
          deviceModel: "iPhone 12",
          deviceYear: "2020",
          appVersion: "1.0.0",
        },
        tags: [{ key: "generated", value: "true" }],
        description: "Automatically generated transaction",
      });

      await newTransaction.save();
      console.log("Transaction generated:", newTransaction.transactionId);
    } catch (error) {
      console.error("Failed to generate transaction:", error);
    }
  });

  console.log("Transaction generator started.");
};

export const stopTransactionGenerator = () => {
  if (task) {
    task.stop();
    task = null;
    console.log("Transaction generator stopped.");
  } else {
    console.log("Transaction generator is not running.");
  }
};
